__version__ = '0.1.3'
__title__ = 'dadjokes-cli'
__description__ = 'Dad Jokes on your Terminal'
__author__ = 'sangarshanan'
__author_email__= 'sangarshanan1998@gmail.com'
__url__ = 'https://github.com/Sangarshanan/dadjokes-cli'